### ISSUE TITLE
Does not compile on Flutter >=3.23

### ISSUE THREAD

**Issue by Cyberczy** [mulaRahul/keyviz#335]
**Describe the bug**
Does not compile on Flutter >=3.23

**Version**: v2.0.0a2

**To Reproduce**
Compilation failed

**Expected behavior**
Compilation successful

**Screenshots**
With certain Linux package repositories removing support for Flutter 3.22 (e.g. Nixpkgs), keyviz is currently unbuildable (see logs below):
```shell
[        ] [+1354 ms] /nix/store/v1c3lns0bway88x1ysngcafdhzjl086z-pub-win32-5.4.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
[        ] [   +1 ms]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [+1606 ms] /nix/store/7ycxxa3birprz2vgslsbwwqy6k5bvlvc-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbow'.
[        ] [        ]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                       ^^^^^^^^^^^^^
[        ] [        ] /nix/store/7ycxxa3birprz2vgslsbwwqy6k5bvlvc-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitSalad'.
[        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                          ^^^^^^^^^^^^^^^^
[        ] [+2596 ms] /nix/store/v1c3lns0bway88x1ysngcafdhzjl086z-pub-win32-5.4.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
[        ] [        ]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] /nix/store/v1c3lns0bway88x1ysngcafdhzjl086z-pub-win32-5.4.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(guid));
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] /nix/store/v1c3lns0bway88x1ysngcafdhzjl086z-pub-win32-5.4.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
[        ] [        ]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] /nix/store/v1c3lns0bway88x1ysngcafdhzjl086z-pub-win32-5.4.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
```

**Desktop (please complete the following information):**
 - NixOS 24.11

**Additional context**
It appears that updating Flutter SDK and other dependencies would solve the issue.
See similar issues at https://github.com/NixOS/nixpkgs/issues/341893

**Comment by sbeyer** [comment]
I get similar errors under Fedora Workstation 41 with Flutter 3.27.1:

```
$ flutter build linux

ERROR: ../../.pub-cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
ERROR:   final UnmodifiableUint8ListView bytes;
ERROR:         ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
ERROR:   final UnmodifiableUint8ListView bytes;
ERROR:         ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
ERROR:     return Guid(UnmodifiableUint8ListView(guid));
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
ERROR:   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
ERROR:                               ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../.pub-cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
ERROR:     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: Target kernel_snapshot_program failed: Exception
Building Linux application...                                           
Build process failed
```

This is my output of `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on Fedora Linux 41 (Workstation Edition) 6.12.6-200.fc41.x86_64, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

So Linux builds should be fine,,,

**Comment by sbeyer** [comment]
I figured out two solutions (without any knowledge of flutter):

1. remove the `win32` entry from `pubspec.lock`
2. remove the whole file `pubspec.lock`

Both version worked for me but resulted in different results (according to `git diff`) after the `flutter build linux`.

Maybe this helps @Cyberczy

I suspect that the contained `pubspec.lock` file is for a Windows build which doesn't make sense under Linux, that's where the issue comes from.
